INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
INF MiPkg/Protocol/MiToken/MiToken.inf
INF QcomPkg/Drivers/TzDxe/ScmDxeLA.inf
INF QcomPkg/Drivers/TzDxe/TzDxeLA.inf
INF QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/RscRtDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SCHandlerRtDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF QcomPkg/Drivers/QcomMpmTimerDxe/QcomMpmTimerDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/VcsDxe/VcsDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/UFSDxe/UFSDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/MinidumpTADxe/MinidumpTADxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/AdcDxe/AdcDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/HashDxe/HashDxe.inf
INF QcomPkg/Drivers/CipherDxe/CipherDxe.inf
INF QcomPkg/Drivers/MacDxe/MacDxe.inf
INF QcomPkg/SocPkg/StraitPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}


FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "logo1.bmp"
    SECTION RAW = RawFiles/logo1.bmp
}


FILE FREEFORM = 02E0AF91-5D44-424F-828F-211ADC520B0C {
    SECTION UI = "Panel_rm69299_amoled_fhd_plus_cmd.xml"
    SECTION RAW = RawFiles/Panel_rm69299_amoled_fhd_plus_cmd.xml
}


FILE FREEFORM = 9BAE75D9-A217-4B31-9DCD-00D2609BC6AE {
    SECTION UI = "Panel_rm69299_amoled_fhd_plus_video.xml"
    SECTION RAW = RawFiles/Panel_rm69299_amoled_fhd_plus_video.xml
}


FILE FREEFORM = 8297C793-9861-422C-9F67-D447AF1EA812 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 44B09226-C2B4-45ED-AA6F-6686DB103978 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = AC31A585-43D1-47CC-9199-D2D6AD994187 {
    SECTION UI = "Panel_r66451_90hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_r66451_90hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 53FD4CBA-F979-492E-ACAD-3F1AA23E9994 {
    SECTION UI = "Panel_r66451_90hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_r66451_90hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 9874B60A-6B80-4D76-8EEB-7862C780EC03 {
    SECTION UI = "Panel_r66451_144hz_fhd_plus_dsc_cmd_cphy.xml"
    SECTION RAW = RawFiles/Panel_r66451_144hz_fhd_plus_dsc_cmd_cphy.xml
}


FILE FREEFORM = 0256CEAF-99CF-49F4-A9C8-D9F1755A5E6C {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd_cphy.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd_cphy.xml
}


FILE FREEFORM = 0256CEAF-99CF-49F4-A9C8-D9F1755A5E70 {
    SECTION UI = "Panel_nt36672e_fhd_plus_60hz_vid.xml"
    SECTION RAW = RawFiles/Panel_nt36672e_fhd_plus_60hz_vid.xml
}


FILE FREEFORM = 0256CEAF-99CF-49F4-A9C8-D9F1755A5E71 {
    SECTION UI = "Panel_nt36672e_fhd_plus_120hz_vid.xml"
    SECTION RAW = RawFiles/Panel_nt36672e_fhd_plus_120hz_vid.xml
}


FILE FREEFORM = 0256CEAF-99CF-49F4-A9C8-D9F1755A5E6F {
    SECTION UI = "Panel_nt36672e_fhd_plus_144hz_vid.xml"
    SECTION RAW = RawFiles/Panel_nt36672e_fhd_plus_144hz_vid.xml
}


FILE FREEFORM = 0256CEAF-99CF-49F4-A9C8-D9F1755A5E6D {
    SECTION UI = "Panel_nt36672e_fhd_plus_144hz_vid_cphy.xml"
    SECTION RAW = RawFiles/Panel_nt36672e_fhd_plus_144hz_vid_cphy.xml
}


FILE FREEFORM = B72827B9-677F-40EB-8368-A23DF6EE309F {
    SECTION UI = "Panel_m17_38_0c_0a_fhdp_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_m17_38_0c_0a_fhdp_dsc_vid.xml
}


FILE FREEFORM = 23CCAC1D-55F5-4DA6-ADE0-D5F81E3CE211 {
    SECTION UI = "Panel_m17_k6s_38_0c_0a_fhdp_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_m17_k6s_38_0c_0a_fhdp_dsc_vid.xml
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
    SECTION UI = "QcomChargerCfg.cfg"
    SECTION RAW = RawFiles/QcomChargerCfg.cfg
}


FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
    SECTION UI = "BATTERY.PROVISION"
    SECTION RAW = RawFiles/BATTERY.PROVISION
}

INF EmbeddedPkg/Ebl/Ebl.inf
